language: node_js
node_js:
  - "9.11"
cache :
  yarn: true

before_install:
  - npm install -g yarn

branches:
  only:
    - master

script:
  - yarn test
  - yarn build

before_deploy:
  - rm -rf node_modules
  - zip -r test ./*
  - mkdir -p deploy
  - mv test.zip deploy/test.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: test-willson
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: willson-appjam/WillSon-Server
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: test-willson
    key: test.zip # 해당 버킷에 저장되어 있는 파일 이름
    bundle_type: zip
    deployment_group: test
    application: test
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: willson-appjam/WillSon-Server
      branch: master

notifications:
  email:
    recipients:
      - 30032dongsu@gmail.com